server:
  port: 8080

spring:
  application:
    name: exchange-rate
  datasource:
    username: juke
    password: password
    url: jdbc:postgresql://localhost:5432/exchange-rate
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: true